var DEVELOPMENT_ADDRESS = 'mongodb://127.0.0.1:';
var DEVELOPMENT_PORT = 27017;
var DEVELOPMENT_DATABASE = 'foodtruckstest';
exports.CONNECTION_STRING = DEVELOPMENT_ADDRESS + DEVELOPMENT_PORT +
    '/' + DEVELOPMENT_DATABASE;